# Traffic Problem
### Google Hash Code 2021 Qualification Round

In [22]:
import pandas as pd
import numpy as np

#### Defined some variables to take in the inputs as a file rather than stdin

In [23]:
# Input Cell

file = open("a.txt", "r")
f1 = file.readlines()
#print(f1)
k = f1[0].rstrip('\n')

l = ''
for i in range(1, int(k.split()[2])+1):
    l = l + f1[i]

m = ''
for j in range(int(k.split()[2]) + 1 , int(k.split()[2]) + int(f1[0].split()[3])+1):
    m = m + f1[j]

print(k)
print(l)
print(m)

6 4 5 2 1000
2 0 rue-de-londres 1
0 1 rue-d-amsterdam 1
3 1 rue-d-athenes 1
2 3 rue-de-rome 2
1 2 rue-de-moscou 3

4 rue-de-londres rue-d-amsterdam rue-de-moscou rue-de-rome
3 rue-d-athenes rue-de-moscou rue-de-londres



## TAKING INPUTS

1) Unloading from the above taken variables
2) Splitting the inputs into multiple lines, if they contain more than one line
3) Creatig a Pandas DataFrame and Adding one-by-one

In [24]:
#taking inputs

#first line of input
global duration,intersection,streets,vehicles,bonus
(duration,intersection,streets,vehicles,bonus) = map(int,k.split())


#taking second line of input


streetsLine = l.split("\n")[:-1]
print(streetsLine)
#creating streets DataFrame
streetIndex = pd.DataFrame(columns = ['Start', 'End', 'Name','Time'],
index = list(range(len(streetsLine))))

#position loc tracker
i = 0

for eachLine in streetsLine:
    print(eachLine.split(" "))
    (start, end, name, time) = eachLine.split(" ")
    temp = []
    temp.append(int(start))
    temp.append(int(end))
    temp.append(name)
    temp.append(int(time))

    streetIndex.loc[i] = temp
    i += 1


#created numpy array to manipulate and use its values
streetIndexArr = np.array(streetIndex)

['2 0 rue-de-londres 1', '0 1 rue-d-amsterdam 1', '3 1 rue-d-athenes 1', '2 3 rue-de-rome 2', '1 2 rue-de-moscou 3']
['2', '0', 'rue-de-londres', '1']
['0', '1', 'rue-d-amsterdam', '1']
['3', '1', 'rue-d-athenes', '1']
['2', '3', 'rue-de-rome', '2']
['1', '2', 'rue-de-moscou', '3']


In [25]:
#some useful functions
def IndexOf(array,name, j):
    # j is position of name in the 2D array
    for i in range(len(array)):
        if streetIndexArr[i][j] == name:
            return i


def addRow(array):
    (rows,col) = array.shape
    array = np.append(array,np.zeros((1,rows),dtype=int), axis = 0)
    return array


def NextIntrevalRow(array):
    (row,col) = array.shape
    #print(row,col)
    k = np.zeros((row,1),dtype = int)
    k[0] = col-1
    array = np.append(array,k,axis = 1)
    return array



In [26]:
#taking vehicle details input

vehicleLine = m.split("\n")[:-1]
VehiclePaths = pd.DataFrame(columns = ['No of Paths', 'PathsName','PathIndices','Path'],
                            index = list(range(len(vehicleLine))))

#position loc tracker
i = 0

for eachVehicle in vehicleLine:
    carDat = eachVehicle.split()
    temp = []
    temp.append(carDat[0])
    temp.append(carDat[1:])
    
    #to get path indices ie indexes of path according to street Indices
    pathIndex = []
    for path in carDat[1:]:
        index = IndexOf(streetIndexArr,path,2)
        pathIndex.append(index)
    
    temp.append(pathIndex)

    pathStr = ""
    k = 0 #defined to show path 1-0- in paths only for initial path, after that everything will be shown as 2-,3- etc
    for path in carDat[1:]:
        index = IndexOf(streetIndexArr,path,2)
        if k==0:
            pathStr += str(streetIndexArr[index][0]) + "-" + str(streetIndexArr[index][1]) + "-"
            k+= 1
        else:
            pathStr += str(streetIndexArr[index][1]) + "-"

    temp.append(pathStr)


    VehiclePaths.loc[i] = temp
    i += 1

#created a numpy array to manipulate its values
VehiclePathsArr = np.array(VehiclePaths)

C:\Users\nfemi\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\internals\blocks.py:983: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_value = np.array(value)


In [27]:
streetIndex

Start End             Name Time
0     2   0   rue-de-londres    1
1     0   1  rue-d-amsterdam    1
2     3   1    rue-d-athenes    1
3     2   3      rue-de-rome    2
4     1   2    rue-de-moscou    3

In [28]:
VehiclePaths

No of Paths                                          PathsName  \
0           4  [rue-de-londres, rue-d-amsterdam, rue-de-mosco...   
1           3     [rue-d-athenes, rue-de-moscou, rue-de-londres]   

    PathIndices        Path  
0  [0, 1, 4, 3]  2-0-1-2-3-  
1     [2, 4, 0]    3-1-2-0-

## Simulation Part -  1

creating TRACK TABLES

In [29]:
#FOR Intersection/TIME TABLE

nodes = [i for i in range(intersection)]
noOfNodes = len(nodes)

rows = np.array([nodes])
rows.resize((noOfNodes,1))
#print(rows.shape)
IntersectionTime = np.empty((intersection,duration+1))
IntersectionTime.fill(-1)
#print(IntersectionTime.shape)
IntersectionTime = np.append(rows,IntersectionTime,axis=1)
IntersectionTime = np.array(IntersectionTime,dtype=int)
IntersectionTime


array([[ 0, -1, -1, -1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1, -1, -1, -1],
       [ 2, -1, -1, -1, -1, -1, -1, -1],
       [ 3, -1, -1, -1, -1, -1, -1, -1]])

In [30]:
cars = [i for i in range(vehicles)]
noOfCars = vehicles
row = np.array([cars])
row.resize((noOfCars,1))
row.shape
#duration +1 to get time for 0 -> duration sec
CarTime = np.empty((vehicles,duration+1))
CarTime.fill(-1)
CarTime = np.append(row,CarTime,axis=1)
CarTime = np.array(CarTime,dtype=int)
CarTime

array([[ 0, -1, -1, -1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1, -1, -1, -1]])

In [31]:
VehiclePaths

No of Paths                                          PathsName  \
0           4  [rue-de-londres, rue-d-amsterdam, rue-de-mosco...   
1           3     [rue-d-athenes, rue-de-moscou, rue-de-londres]   

    PathIndices        Path  
0  [0, 1, 4, 3]  2-0-1-2-3-  
1     [2, 4, 0]    3-1-2-0-

In [32]:
streetIndex

Start End             Name Time
0     2   0   rue-de-londres    1
1     0   1  rue-d-amsterdam    1
2     3   1    rue-d-athenes    1
3     2   3      rue-de-rome    2
4     1   2    rue-de-moscou    3

## Scoring Function

In [33]:
#Output

# NO OF INTERSECTION
#for each intersection:
#   ID
#   NO OF INCOMING STREETS
#   FOR EACH INCOMING STREETS:
#       NAME GREEN_LIGHT_DURATION

#Scoring

# F + (D-T)
# Bonus + (Duration - TimeSpentToComplete)

In [34]:
def score(text):

    #Taking inputs 
    #-----------------------------------------------------------------------
    collector = text.split()
    #creating an indexing iterator to grab data
    k = 0
    NoOfIntesections = int(collector[k])
    k += 1
    IntersectionData = []
    for i in range(NoOfIntesections):
        ID = int(collector[k])
        k += 1
        NoOfIncomingStreets = int(collector[k])
        k += 1
        IncStreetData = []
        for j in range(NoOfIncomingStreets):
            name = collector[k]
            k += 1
            duration = int(collector[k])
            k += 1
            IncStreetData.append((name,duration))
        
        IntersectionData.append((ID,NoOfIncomingStreets,IncStreetData))
        #print(IntersectionData)

    #Inputs gathering finishes
    #------------------------------------------------------------------------------------

    #finding T
    # T = time taken by each car

    

    #score = (bonus + (duration-t))
    pass


In [35]:
def Score2(timeList):
    global duration
    global bonus
    times = []
    for i in timeList:
        if i <= duration:
            times.append(i)

    timesArr = np.array(times)
    
    cars = len(timesArr)
    score = (cars*(bonus+duration)) - timesArr.sum()

    return score

In [36]:
text = '''
3
1
2
rue-d-athenes 2
rue-d-amsterdam 1
0
1
rue-de-londres 2
2
1
rue-de-moscou 1
'''

In [37]:
score(text)

In [38]:
time = [4,7]
print(Score2(time))

1002


## Simulation Part - 1
### Creating Car Objects

Scheduler

In [39]:
VehiclePaths

No of Paths                                          PathsName  \
0           4  [rue-de-londres, rue-d-amsterdam, rue-de-mosco...   
1           3     [rue-d-athenes, rue-de-moscou, rue-de-londres]   

    PathIndices        Path  
0  [0, 1, 4, 3]  2-0-1-2-3-  
1     [2, 4, 0]    3-1-2-0-

In [40]:
class Car:
    loc = 0
    TimeUsed = 0

    def __init__(self,index,path,gas):
        self.index = index
        self.path = path
        self.loc = path[0]
        Car.gas = gas


    def move(self):
        if Car.loc < len(self.path)-1:
            Car.loc += 1
            #print(Car.loc)
            Car.TimeUsed += Car.gas[(Car.loc)-1]
            #print("Time : "+str(Car.TimeUsed))
            self.loc = self.path[Car.loc]
            #print("Car Moved to "+str(self.loc))
        else:
            #print("Path Over")
            pass

    def PassTime(self,dur):
        Car.TimeUsed += dur
    
    def ShowLocation(self):
        return self.loc

    def ShowTimeUsed(self):
        return Car.TimeUsed

    def PrintStats(self):
        print("Location : "+ str(self.ShowLocation()))
        print("Time Spent : "+ str(self.ShowTimeUsed()))

    def printPath(self):
        print(self.path)

In [41]:
#scheduler tracks events in the board at every intr
global TimeE
TimeE = 0

'''
schedule:
Node 1 : 2 for athens
        : 1 for amsterdam

Node 0 : 1 sec for londres

Node 2 : 1 sec for  moscow
'''

#INITIALIZING Vehicle path
path = VehiclePathsArr[0][3].split("-")
path.pop()
path = list(map(int,path))
gas = []

for k in VehiclePathsArr[0][2]:
    gas.append(streetIndexArr[k][3])

#initializing the Car
carA = Car(0,path,gas)


TimeE = 0
green = 1
while (TimeE <= duration):
    CarTime[carA.index][TimeE+1] = carA.loc
    if green == 1:
        carA.PassTime(1)
        carA.move()
        TimeE = carA.TimeUsed
        #print(TimeE)
    else:
        print("hello")
        #waiting in traffic
        carA.PassTime(1)
        #moving through traffic
        carA.PassTime(1)
        TimeE = carA.TimeUsed
CarTime


array([[ 0,  2,  0,  1, -1, -1, -1,  2],
       [ 1, -1, -1, -1, -1, -1, -1, -1]])